

/* Create Tables */

CREATE TABLE USERS
(
	USER_ID CHAR(36) NOT NULL COMMENT 'ユーザーID',
	USER_NAME VARCHAR(50) NOT NULL COMMENT 'ユーザーネーム',
	EMAIL VARCHAR(100) NOT NULL COMMENT 'メールアドレス',
	CREATED_AT DATETIME NOT NULL COMMENT '登録日時',
	UPDATED_AT DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO INT NOT NULL COMMENT 'バージョンナンバー',
	PRIMARY KEY (USER_ID)
) COMMENT = 'ユーザー';



